variables:
  DEPLOY_OWNER_PRIVKEY: 0xBF3862CD1EE53F542C483E4F55BEE2D0B13014A7D6AD1B0CA457240C2888C1FB

image: node:14-buster

stages:
  - build
  - test
  - analysis
  - deploy

default:
  tags:
    - docker
  cache:
    key: ${CI_PROJECT_PATH_SLUG}
    paths:
      - node_modules/
      - artifacts/
      - cache/
  before_script:
    - npm install

build:
  stage: build
  script:
    - npm run build
    - npm run check

.test_job: &test_job
  stage: test
  script:
    - apt-get update && apt-get install -y netcat
    - RUNNER_COUNT=12
    - FILES=( $(find -H -L ./test/* -regex "^.*.test.js") )
    - len=${#FILES[@]}
    - >
      for (( i=0; i<${RUNNER_COUNT}; i+=1 )); do
          RUNNER_TEST_CNTS[$i]=0
      done
    - >
      for (( i=0; i<${len}; i+=1 )); do
          TestCases[$i]=$(grep -o " it" ${FILES[$i]} | wc -l)
      done
    - >
      for ((i = 0; i<${len}; i++))
      do
          for((j = 0; j<${len}-i-1; j++))
          do
              if [ ${TestCases[j]} -lt ${TestCases[$((j+1))]} ]
              then
                  # swap
                  temp=${TestCases[j]}
                  TestCases[$j]=${TestCases[$((j+1))]}
                  TestCases[$((j+1))]=$temp

                  temp=${FILES[j]}
                  FILES[$j]=${FILES[$((j+1))]}
                  FILES[$((j+1))]=$temp
              fi
          done
      done
    - MIN=${RUNNER_TEST_CNTS[0]}
    - MINIDX=0
    - >
      for (( i=0; i<${len}; i+=1 )); do
          for j in ${!RUNNER_TEST_CNTS[@]};
          do
              if [ ${MIN} -gt ${RUNNER_TEST_CNTS[$j]} ]
              then
                  MIN=${RUNNER_TEST_CNTS[${j}]}
                  MINIDX=${j}
              fi
          done

          UNITTEST_FILES[$MINIDX]+=' '"${FILES[$i]}"
          RUNNER_TEST_CNTS[$MINIDX]=`expr ${TestCases[$i]} + ${RUNNER_TEST_CNTS[$MINIDX]}`
          MIN=${RUNNER_TEST_CNTS[$MINIDX]}
      done
    - npm run test ${UNITTEST_FILES[${JOB_INDEX}]}

test_0:
  variables:
    JOB_INDEX: 0
  <<: *test_job

test_1:
  variables:
    JOB_INDEX: 1
  <<: *test_job

test_2:
  variables:
    JOB_INDEX: 2
  <<: *test_job

test_3:
  variables:
    JOB_INDEX: 3
  <<: *test_job

test_4:
  variables:
    JOB_INDEX: 4
  <<: *test_job

test_5:
  variables:
    JOB_INDEX: 5
  <<: *test_job

test_6:
  variables:
    JOB_INDEX: 6
  <<: *test_job

test_7:
  variables:
    JOB_INDEX: 7
  <<: *test_job

test_8:
  variables:
    JOB_INDEX: 8
  <<: *test_job

test_9:
  variables:
    JOB_INDEX: 9
  <<: *test_job

test_10:
  variables:
    JOB_INDEX: 10
  <<: *test_job

test_11:
  variables:
    JOB_INDEX: 11
  <<: *test_job

analysis_slither:
  stage: analysis
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install slither-analyzer && pip3 install solc-select
    - npm run analysis

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y netcat
    - npm run deploy
